# Generated by Django 5.2.1 on 2025-05-16 23:32

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_articulo_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='foto',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
