# Generated by Django 5.2.1 on 2025-05-17 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_alter_articulo_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='categoria',
            field=models.CharField(default='Sin categoria', max_length=255),
            preserve_default=False,
        ),
    ]
